### ISSUE TITLE
new BigNumber() not a number: 0aN

### ISSUE THREAD

**Issue by s-a-y** [stellar-expert/albedo#68]
Trying to use Albedo to make deposits into liquidity pools, founds few bugs, this is number 2

When you choose assets for which liquidity pool exists but has 0 balances

```
"new BigNumber() not a number: 0aN" at https://albedo.link/wallet/liquidity-pool/deposit
BigNumber Error: new BigNumber() not a number: 0aN
    at ee (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:321134)
    at r (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:326614)
    at new V (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:319036)
    at M (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:108273)
    at Q (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:108055)
    at F (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:108843)
    at le (https://albedo.link/882.js:1:27260)
    at oa (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:798235)
    at Gs (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:850474)
    at Su (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:837680)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
```

**Comment by orbitlens** [comment]
Fixed. Thanks for the heads up! 🤝
