### ISSUE TITLE
Creating liquidity pool fails

### ISSUE THREAD

**Issue by s-a-y** [stellar-expert/albedo#69]
Trying to use Albedo to make deposits into liquidity pools, founds few bugs, this is number 3

Trying to create liquidity pool that does not yet exist

<img width="594" alt="Screen Shot 2021-11-05 at 9 34 32 PM" src="https://user-images.githubusercontent.com/1667781/140497659-8e4efc16-dad0-489a-9ba1-2fbb1185b43f.png">

Transaction fails

<img width="511" alt="Screen Shot 2021-11-05 at 9 34 52 PM" src="https://user-images.githubusercontent.com/1667781/140497645-719af92a-ca57-4959-b497-63e6f3995bcd.png">

stellar.expert also doesn't show it correctly
https://stellar.expert/explorer/public/tx/e3470d700a9fb569a71205e5dfbe7c826399e6479e8c6bf88b3c1d2d42c0e39f

```
"Invalid asset name: undefined." at https://stellar.expert/explorer/public/tx/e3470d700a9fb569a71205e5dfbe7c826399e6479e8c6bf88b3c1d2d42c0e39f
TypeError: Invalid asset name: undefined.
    at new s (https://stellar.expert/distr/app.js?v=0.18.4:2:39736)
    at Function.parse (https://stellar.expert/distr/app.js?v=0.18.4:2:41144)
    at a (https://stellar.expert/distr/explorer.js:1:105112)
    at T (https://stellar.expert/distr/explorer.js:1:107917)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
```

**Comment by shankara51** [comment]
Error
