### ISSUE TITLE
Balances page fails when you have trustline to liquidity pool with 0 balance

### ISSUE THREAD

**Issue by s-a-y** [stellar-expert/albedo#70]
Trying to use Albedo to make deposits into liquidity pools, founds few bugs, this is number 4

Created trustline to liquidity pool outside of albedo, now trying to see balances and the whole page crashes with

```
"Cannot read properties of null (reading '0')" at https://albedo.link/account
TypeError: Cannot read properties of null (reading '0')
    at d (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:270659)
    at oa (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:798235)
    at Gs (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:850474)
    at Su (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:837680)
    at Cu (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:837608)
    at Iu (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:837471)
    at mu (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:834458)
    at https://albedo.link/albedo.62186c4a6b59acf85160.js:2:784130
    at t.unstable_runWithPriority (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:941266)
    at Ko (https://albedo.link/albedo.62186c4a6b59acf85160.js:2:783907)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
```

**Comment by orbitlens** [comment]
Fixed. Thanks for the heads up! 🤝
